# Generated by Django 4.1.2 on 2022-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, verbose_name='pais')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='nacionalidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='pais',
        ),
    ]
