# Generated by Django 4.1.2 on 2022-10-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0010_persona_nacionalidadp_alter_persona_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(verbose_name='nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='paisp',
            field=models.CharField(choices=[(1, 'Afganistán'), (2, 'Albania'), (3, 'Alemania'), (4, 'Andorra'), (5, 'Angola'), (6, 'AntiguayBarbuda'), (7, 'ArabiaSaudita'), (8, 'Argelia'), (9, 'Argentina'), (10, 'Armenia'), (11, 'Aruba'), (12, 'Australia'), (13, 'Austria'), (14, 'Azerbaiyán'), (15, 'Bahamas'), (16, 'Bangladés'), (17, 'Barbados'), (18, 'Baréin'), (19, 'Bélgica'), (20, 'Belice'), (21, 'Benín'), (22, 'Bielorrusia'), (23, 'Birmania'), (24, 'Bolivia'), (25, 'BosniayHerzegovina'), (26, 'Botsuana'), (27, 'Brasil'), (28, 'Brunéi'), (29, 'Bulgaria'), (30, 'BurkinaFaso'), (31, 'Burundi'), (32, 'Bután'), (33, 'CaboVerde'), (34, 'Camboya'), (35, 'Camerún'), (36, 'Canadá'), (37, 'Catar'), (38, 'Chad'), (39, 'Chile'), (40, 'China'), (41, 'Chipre'), (42, 'CiudaddelVaticano'), (43, 'Colombia'), (44, 'Comoras'), (45, 'CoreadelNorte'), (46, 'CoreadelSur'), (47, 'CostadeMarfil'), (48, 'CostaRica'), (49, 'Croacia'), (50, 'Cuba'), (51, 'Dinamarca'), (52, 'Dominica'), (53, 'Ecuador'), (54, 'Egipto'), (55, 'ElSalvador'), (56, 'EmiratosÁrabesUnidos'), (57, 'Eritrea'), (58, 'Eslovaquia'), (59, 'Eslovenia'), (60, 'España'), (61, 'EstadosUnidos'), (62, 'Estonia'), (63, 'Etiopía'), (64, 'Filipinas'), (65, 'Finlandia'), (66, 'Fiyi'), (67, 'Francia'), (68, 'Gabón'), (69, 'Gambia'), (70, 'Georgia'), (71, 'Gibraltar'), (72, 'Ghana'), (73, 'Granada'), (74, 'Grecia'), (75, 'Groenlandia'), (76, 'Guatemala'), (77, 'Guineaecuatorial'), (78, 'Guinea'), (79, 'Guinea-Bisáu'), (80, 'Guyana'), (81, 'Haití'), (82, 'Honduras'), (83, 'Hungría'), (84, 'India'), (85, 'Indonesia'), (86, 'Irak'), (87, 'Irán'), (88, 'Irlanda'), (89, 'Islandia'), (90, 'IslasCook'), (91, 'IslasMarshall'), (92, 'IslasSalomón'), (93, 'Israel'), (94, 'Italia'), (95, 'Jamaica'), (96, 'Japón'), (97, 'Jordania'), (98, 'Kazajistán'), (99, 'Kenia'), (100, 'Kirguistán'), (101, 'Kiribati'), (102, 'Kuwait'), (103, 'Laos'), (104, 'Lesoto'), (105, 'Letonia'), (106, 'Líbano'), (107, 'Liberia'), (108, 'Libia'), (109, 'Liechtenstein'), (110, 'Lituania'), (111, 'Luxemburgo'), (112, 'Madagascar'), (113, 'Malasia'), (114, 'Malaui'), (115, 'Maldivas'), (116, 'Malí'), (117, 'Malta'), (118, 'Marruecos'), (119, 'Martinica'), (120, 'Mauricio'), (121, 'Mauritania'), (122, 'México'), (123, 'Micronesia'), (124, 'Moldavia'), (125, 'Mónaco'), (126, 'Mongolia'), (127, 'Montenegro'), (128, 'Mozambique'), (129, 'Namibia'), (130, 'Nauru'), (131, 'Nepal'), (132, 'Nicaragua'), (133, 'Níger'), (134, 'Nigeria'), (135, 'Noruega'), (136, 'NuevaZelanda'), (137, 'Omán'), (138, 'PaísesBajos'), (139, 'Pakistán'), (140, 'Palaos'), (141, 'Palestina'), (142, 'Panamá'), (143, 'PapúaNuevaGuinea'), (144, 'Paraguay'), (145, 'Perú'), (146, 'Polonia'), (147, 'Portugal'), (148, 'PuertoRico'), (149, 'ReinoUnido'), (150, 'RepúblicaCentroafricana'), (151, 'RepúblicaCheca'), (152, 'RepúblicadeMacedonia'), (153, 'RepúblicadelCongo'), (154, 'RepúblicaDemocráticadelCongo'), (155, 'RepúblicaDominicana'), (156, 'RepúblicaSudafricana'), (157, 'Ruanda'), (158, 'Rumanía'), (159, 'Rusia'), (160, 'Samoa'), (161, 'SanCristóbalyNieves'), (162, 'SanMarino'), (163, 'SanVicenteylasGranadinas'), (164, 'SantaLucía'), (165, 'SantoToméyPríncipe'), (166, 'Senegal'), (167, 'Serbia'), (168, 'Seychelles'), (169, 'SierraLeona'), (170, 'Singapur'), (171, 'Siria'), (172, 'Somalia'), (173, 'SriLanka'), (174, 'Suazilandia'), (175, 'SudándelSur'), (176, 'Sudán'), (177, 'Suecia'), (178, 'Suiza'), (179, 'Surinam'), (180, 'Tailandia'), (181, 'Tanzania'), (182, 'Tayikistán'), (183, 'TimorOriental'), (184, 'Togo'), (185, 'Tonga'), (186, 'TrinidadyTobago'), (187, 'Túnez'), (188, 'Turkmenistán'), (189, 'Turquía'), (190, 'Tuvalu'), (191, 'Ucrania'), (192, 'Uganda'), (193, 'Uruguay'), (194, 'Uzbekistán'), (195, 'Vanuatu'), (196, 'Venezuela'), (197, 'Vietnam'), (198, 'Yemen'), (199, 'Yibuti'), (200, 'Zambia'), (201, 'Zimbabue')], max_length=100, verbose_name='pais'),
        ),
    ]
