# Generated by Django 4.1.2 on 2022-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_persona_paisp_alter_persona_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(verbose_name='nacimiento'),
        ),
    ]
