# Generated by Django 4.1.2 on 2022-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_alter_persona_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='ISOnac',
            field=models.CharField(default=True, max_length=100, verbose_name='ISOnac'),
            preserve_default=False,
        ),
    ]
