# Generated by Django 4.1.2 on 2022-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_alter_persona_paisp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='idp',
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
