# Generated by Django 4.1.2 on 2022-10-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0009_alter_persona_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacionalidadp',
            field=models.CharField(default=True, max_length=100, verbose_name='nacionalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(verbose_name='nacimiento (yyyy-mm-dd)'),
        ),
    ]
