# Generated by Django 4.1.2 on 2022-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0012_alter_persona_paisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='paisp',
            field=models.CharField(max_length=100, verbose_name='pais'),
        ),
    ]
